### ISSUE TITLE
Bootstrap resampling without replacement

### ISSUE THREAD

**Issue by pmichel31415** [neulab/compare-mt#108]
According to my understanding (and the original paper: https://www.aclweb.org/anthology/W04-3250), bootstrap resampling should be performed **with replacement**.

However If I understand the current code  we are sampling without replacement. This is probably not going to change actual results that much but we should still fix it for the sake of consistency (for instance one instance where sampling without replacement goes wring is that the more you increase the number of samples the less accurate the confidence intervals become).

EDIT: I think those are the lines where we are sampling: https://github.com/neulab/compare-mt/blob/master/compare_mt/sign_utils.py#L47-L48

Instead we should do

```python
reduced_ids = np.random.choice(ids, size=int(len(ids)*sample_ratio), replace=True)
```

**Comment by zdou0830** [comment]
Hi, I'm not sure but I think we are sampling with replacement right now, as `ids` won't change after each step. Your code seems more elegant though so maybe we can use that.

Speaking of which, do you think we need to set a random seed so that the output p-value is consistent?

**Comment by pmichel31415** [comment]
What I mean by without replacement is that (unless I'm reading the code wrong), `reduced_ids` will never contain duplicates. In other words it's not just that we need to replace `reduced_ids` after sampling but when sampling `reduced_ids` we need to replace each ID we sample (otherwise the samples are not independent)

**Comment by pmichel31415** [comment]
Re: random seed

I think the most appropriate behaviour would be to not fix the random seed by default and allow people to specify one if they want to. That being said with enough samples the results should be fairly stable so I don't think that this is that critical a feature (but if you have time go ahead)

**Comment by zdou0830** [comment]
Ah, you are right. I agree that we should change that.

**Comment by neubig** [comment]
Wow, embarrassingly I actually didn't know that this was supposed to be with replacement. It makes sense in hindsight. This definitely should be fixed.
