### ISSUE TITLE
pip install errors

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/compare-mt#127]
When installing compare-mt with pip, usually get following errors:
![image](https://user-images.githubusercontent.com/59123869/152276526-6ed043ef-aaa0-4ebf-81c9-897adc9dbfe1.png)

**Comment by neubig** [comment]
I've confirmed this error and will fix it.

**Comment by neubig** [comment]
The code is fixed but I need to deploy to pypi.

**Comment by pmichel31415** [comment]
Hey, so I took a quick look and if I understand correctly we need to move pypi deployment from travis to github actions right? I'm not 100% sure how seamless the transition will be, I'll try to look into it later this week.

**Comment by neubig** [comment]
I can do it if you give me permission!

**Comment by neubig** [comment]
@pfliu-nlp : should be fixed by version 0.2.9

**Comment by pfliu-nlp** [comment]
Thanks a lot Graham!
