### ISSUE TITLE
Formatting table results

### ISSUE THREAD

**Issue by rooa** [neulab/compare-mt#14]
Do people think it's helpful to format the CLI outputs using some external packages like [tabulate](https://bitbucket.org/astanin/python-tabulate)? Please see an example below.

Also, tabulate can take an argument to generate html outputs, which may also be helpful when considering dumping results in html.

Before:
```
x < -20	0	0
-20 <= x < -10	8	12
-10 <= x < -5	66	67
x = -5	41	44
x = -4	73	58
x = -3	115	97
x = -2	173	187
x = -1	263	256
x = 0	394	423
x = 1	330	344
x = 2	296	275
x = 3	219	194
x = 4	127	153
x = 5	107	93
6 <= x < 11	194	182
11 <= x < 21	39	51
21 < x	0	9
```
After:
```
--------------  ---  ---
x < -20           0    0
-20 <= x < -10    8   12
-10 <= x < -5    66   67
x = -5           41   44
x = -4           73   58
x = -3          115   97
x = -2          173  187
x = -1          263  256
x = 0           394  423
x = 1           330  344
x = 2           296  275
x = 3           219  194
x = 4           127  153
x = 5           107   93
6 <= x < 11     194  182
11 <= x < 21     39   51
21 < x            0    9
--------------  ---  ---
```

ps: If so, adding `requirements.txt` will be in higher demand. (The package already requires `nltk`, which has not been stated in README.)

**Comment by neubig** [comment]
I think this is a good idea, but there actually was a reason that I had it just be TSV, which was that it'd be easier to copy-paste into a spreadsheet for plotting.

I think maybe it'd be good to add this while tackling the bigger issue of separating out generation of statistics from printing, as noted in https://github.com/neulab/compare-mt/issues/6

**Comment by neubig** [comment]
I think given that the HTML report is probably going to be the main report that people are looking at, this might not be so important anymore. I'll close it for now, but thanks for the suggestion!
