### ISSUE TITLE
Analysis of reordering errors

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#16]
It might be nice to have some idea of how many reordering errors are occurring, it's not clear exactly how to do this, but we can discuss.

**Comment by zdou0830** [comment]
Toral and Sánchez-Cartagena [1] used the Kendall's tau distance between word alignments to measure this. I don't think this would be accurate though.

[1] Toral, Antonio, and Víctor M. Sánchez-Cartagena. "A Multifaceted Evaluation of Neural versus Phrase-Based Machine Translation for 9 Language Directions." EACL 2017.

**Comment by neubig** [comment]
I discussed with @JunjieHu about the RIBES evaluation measure, which also is based on Kendall's Tau distance: http://www.anthology.aclweb.org/D/D10/D10-1092.pdf

There is a publicly available implementation, but it's GPL (and I don't want to make compare-mt GPL because it'd limit its usability in other libraries), so we'd have to re-implement it from scratch from the description in the paper.
