### ISSUE TITLE
Consider alignments, making it possible to analyze source words

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#2]
Currently the script does not allow analysis over source words.

It would be nice if we could use alignments to measure the f-measure of source words/n-grams according to various criteria. One example of this is the analysis done by @frederick0329 in the paper [Handling Homographs in Neural Machine Translation](https://arxiv.org/abs/1708.06510)

**Comment by JunjieHu** [comment]
[WIP] I am working on this feature.

**Comment by neubig** [comment]
Actually @zdou0830 already has a PR open: https://github.com/neulab/compare-mt/pull/11
