### ISSUE TITLE
FreqWordBucketer doesn't build the frequency counts correctly from a corpus file

### ISSUE THREAD

**Issue by danishpruthi** [neulab/compare-mt#20]
I think there is a small bug in a way the `freq_counts` is populated from a `freq_corpus_file` in the following lines:

https://github.com/neulab/compare-mt/blob/00af7f4619fd51c3805552acc935bd593fcff216/bucketers.py#L185-L187

The value in `word` is a list of words not the word itself.

PS: I am working on #10, and I can include this fix in the same PR.

**Comment by zdou0830** [comment]
Speaking of which, do we need to support Python 3.5 where f-strings are not supported?

**Comment by neubig** [comment]
Nah. f-strings are super-convenient :)
