### ISSUE TITLE
"external program" Scorer

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#27]
It'd be nice if we could also use METEOR. There are examples of how to use METEOR in Python that we might be able to start from:
https://github.com/hharnisc/python-meteor

**Comment by pmichel31415** [comment]
Just FYI I checked the link you gave and I don't think it has anything to do with MT, seems to be another "meteor". I couldn't really find any pure python implementation of METEOR. Here is a relevant (open) issue for nltk: https://github.com/nltk/nltk/issues/2041

**Comment by neubig** [comment]
One way to do this might be to have the ability to create a scorer that calls an external command, and then the stdout output is a single float per line in the input corpus that we then read in. We could make this an instance of SentenceFactoredScorer. I think it would probably be easy to do this with METEOR, and it would also allow us to use other evaluation metrics that aren't easy to integrate.

**Comment by zdou0830** [comment]
Could we include the code of METEOR into compare-mt? It's released under the GNU Lesser General Public License.

**Comment by pmichel31415** [comment]
Just my 2 cents but I think this would add an unnecessary amount of code to the repo that everyone not using meteor would have to download. Also meteor requires a lot of auxiliary data (paraphrase tables and such). Probably better to just give people the option to specify the path to the meteor jar and data files IMO.

**Comment by neubig** [comment]
Agree with Paul.

**Comment by neubig** [comment]
We have the METEOR scorer now, so I'll close this. We can re-open it if necessary.
