### ISSUE TITLE
Ability to specify more than 2 systems to analyze

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#39]
Currently `compare_mt.py` only works with exactly two systems. It'd be nice if it was possible to specify more than two systems.

For some things this is relatively easy. For example, aggregate score analysis, word accuracy analysis, sentence bucket analysis are all calculated with respect to single systems, so this should be easy.

For other things, like n-gram analysis, and sentence difference analysis, this is harder because the analysis is pairwise. In this case, we might just have to specify which systems to compare.

**Comment by zdou0830** [comment]
I will work on this (after #18 is merged?).

**Comment by neubig** [comment]
Thanks!

**Comment by neubig** [comment]
Fixed by https://github.com/neulab/compare-mt/pull/44
