### ISSUE TITLE
Make number format consistent and configurable

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#50]
Currently the formatting of numbers is not consistent, and also cannot be changed. It would be nice to adjust the following:

* [x] Most places use four digits, but some use 2, and others use default string formatting of Python. It would be nice to be able to specify the number of digits.
* [ ] We can't adjust whether we want to have numbers be multiplied by 100 or not (sometimes this is good for BLEU, as it makes numbers easier to read and tables more concise).
* [x] Integer values should not have decimal places.

This can be worked on once https://github.com/neulab/compare-mt/pull/49 is merged.

**Comment by pmichel31415** [comment]
FYI I started addressing the 1st (and last also I guess) point.

**Comment by neubig** [comment]
I think the middle point isn't so important, so I'll close this.
