### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by pmichel31415** [neulab/compare-mt#64]
It would be convenient for users to be able to `pip install` compare-mt. I'm willing to take care of this but I'd rather wait until things settle down a little bit (especially if we are going to change the name).

In any case, I'll leave this issue up as a reminder

**Comment by neubig** [comment]
I think we'll probably just stick with `compare-mt`, so I think you can set up what's necessary to upload to PyPi.

**Comment by neubig** [comment]
Fixed by https://github.com/neulab/compare-mt/pull/71
