### ISSUE TITLE
ROUGE evaluation measure

### ISSUE THREAD

**Issue by zdou0830** [neulab/compare-mt#66]
Would it be nice to implement ROUGE as it is often used in tasks like text summarization?

**Comment by neubig** [comment]
Yes, we could use this:
https://github.com/google-research/google-research/tree/master/rouge

I'm sure we can include Apache-licensed code within `compare-mt`, so I think we could probably make this the `compare_mt/rogue` directory, and reference it directly from a `Scorer`.

**Comment by pmichel31415** [comment]
If we want to avoid the license issue we can use pyrouge from our vey own @pcyin https://github.com/pcyin/PyRouge

**Comment by neubig** [comment]
Haha, that works too. I think perhaps the Google version implements *all* of ROUGE while @pcyin's version only does a part of it. Maybe he could comment though.

**Comment by neubig** [comment]
@zdou0830 Are you interested in taking a stab at this? It might be nice to have if we want to put summarization results in the paper.

**Comment by zdou0830** [comment]
Sure! I will work on this.

**Comment by zdou0830** [comment]
Hi @neubig, I think the Google version only supports English. I am not very familiar with the license, is it okay to modify their code?

**Comment by neubig** [comment]
Yes, it's OK to modify the code. Modified code would be under the Apache license, while the rest of `compare-mt` would be under the BSD license.

However, I'd suggest that you just incorporate the package as-is for now. Then later if we want to handle languages other than English we can discuss the best way to do so.

**Comment by neubig** [comment]
Fixed by https://github.com/neulab/compare-mt/pull/76
