### ISSUE TITLE
Encoding issues in non-ASCII output?

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#70]
It looks like maybe we have an encoding issue when printing out non-ASCII characters in output. Because I was mainly looking at English I didn't realize, but it's obvious when printing out the Slovak source sentences included in the example. See attached figure.
<img width="730" alt="screen shot 2019-02-08 at 4 31 05 pm" src="https://user-images.githubusercontent.com/398875/52507298-1efa9f80-2bbf-11e9-9922-e7543efa4f61.png">

**Comment by pmichel31415** [comment]
I think this can be solved by this:

```python
def to_html_safe(string):
    return string.encode("ascii","xmlcharrefreplace").decode()
```

cf https://stackoverflow.com/a/2657467

If you give me the command to reproduce the table you showed I can test this and submit a PR

**Comment by zdou0830** [comment]
Hi @pmichel31415, the command is 

`compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --src_file example/ted.orig.slk `
