### ISSUE TITLE
Some measure of bucketed statistic reliability

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#88]
When doing bucketing of either words or sentences, some of the buckets may have very few examples included, and thus the estimates of statistics may not be very reliable. It would be nice to have some idea of the reliability of these, either through:

1. Outputting the number of counts of words/sentences in each bucket
2. Error bars on the estimates calculated through regular standard deviation, or bootstrapping

**Comment by rohitg1594** [comment]
Hi, this would be great to have. Any progress on this?

**Comment by zdou0830** [comment]
Hi @rohitg1594, thanks! Hopefully this will be done by the end of August. Contributions are also welcome!
